version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
